
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey


/**
 * Represents a user in the database.
 *
 * @property id The unique identifier for the user.  This is automatically generated by the database.
 * @property firstName The first name of the user. May be null.
 * @property lastName The last name of the user. May be null.
 */

@Entity(tableName = "users")
data class ModelUser(
    @PrimaryKey(autoGenerate = true) val id: Int? = null,
    @ColumnInfo(name = "first_name") val firstName: String?,
    @ColumnInfo(name = "last_name") val lastName: String?
)

